# Generated by Django 3.2.9 on 2022-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220301_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
