# Generated by Django 3.2.12 on 2022-02-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220223_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
