# Generated by Django 3.2.12 on 2022-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220223_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='Соглашение по отправке уведомлений на почту'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Выберите пол*',
            field=models.CharField(default='male', max_length=30, verbose_name=(('male', 'Мужской пол'), ('female', 'Женский пол'))),
        ),
    ]
