# Generated by Django 3.2.12 on 2022-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220223_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='Мужской пол', max_length=40),
        ),
    ]
